### ISSUE TITLE
somewhere that needs to be modified

### ISSUE THREAD

**Issue by liujuncn** [syncdoth/RetNet#1]
def get_parallel_decay_mask(self, length):

Tensor created in above function is default created on cpu.  If train on cuda, it will throw error like below:

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**Comment by syncdoth** [comment]
You are correct. The recent commit (48a3984008db3daaf564fbd748006517aeb660ee) should solve this issue. Thanks!
