### ISSUE TITLE
Can you provide a LICENCE file

### ISSUE THREAD

**Issue by Shubhankar-Aidetic** [syncdoth/RetNet#13]
I would like to use this repo for my job. I cannot do so until you add a license to the repo. Can you please do so soon?

**Comment by syncdoth** [comment]
I have added an MIT license to the main branch, following the license of `torchscale`, which should contain the official implementation of RetNet. 

Bear in mind; this is NOT the official repo, and I am not the author of the Retentive Network Paper.

**Comment by Shubhankar-Aidetic** [comment]
Hey thanks for the quick update! I understand that this isnt the official repo.
