### ISSUE TITLE
真缺一个全量多卡显存叠加并行训练方案,如果能行也算是一种成功!/ There is really a lack of a full-scale multi-card video memory superposition parallel training scheme. If it can be done, it can be regarded as a success! 

### ISSUE THREAD

**Issue by gg22mm** [syncdoth/RetNet#5]
真缺一个全量多卡显存叠加并行训练方案,如果能行也算是一种成功! / There is really a lack of a full-scale multi-card video memory superposition parallel training scheme. If it can be done, it can be regarded as a success!

**Comment by syncdoth** [comment]
I don't speak Chinese, but from translate it seems that you mentioned multi-gpu parallelization. I haven't tested any of the multi-gpu setup yet (dp, ddp, fsdp), so it's likely that it may fail. I am open to contributions!

**Comment by gg22mm** [comment]
Thank you for your answer

**Comment by gg22mm** [comment]
Let me add: that is, the model runs larger models in parallel with multiple cards   /  我补充一下：也就是模型并行，多卡运行更大的模型
