### ISSUE TITLE
parallel and recurrent forward achieves totally different output

### ISSUE THREAD

**Issue by Zhihan1996** [syncdoth/RetNet#7]
Hey,

Thank you for this great work!

I played with your example code and found that the `rnn_state` and `parallel_state` are totally different. However, based on my understanding of this work, these two states should be the same. Do you have any idea on this issue?

**Comment by syncdoth** [comment]
Are the parallel and recurrent state found in the `play.ipynb` different? If you have a minimal reproducible code, that would be great!

**Comment by syncdoth** [comment]
Please re-open this issue if the problem persists.
